name: Make modified autocommit test

on:
  pull_request:

jobs:
  run-make:
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    uses: Sho2010/gha-auto-comitter/.github/workflows/make-modified-autocommit.yaml@v0.0.1
    with:
      ref: ${{ github.head_ref }}
